# Generated by Django 3.2.4 on 2021-07-20 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=12)),
                ('pin_code', models.CharField(max_length=10)),
                ('building_details', models.CharField(max_length=140)),
                ('area_details', models.CharField(max_length=140)),
                ('landmark_details', models.CharField(max_length=140)),
                ('town_details', models.CharField(max_length=140)),
                ('state', models.CharField(max_length=140)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
