# Generated by Django 3.2.4 on 2021-07-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='area_details',
            new_name='locality_details',
        ),
        migrations.RemoveField(
            model_name='address',
            name='landmark_details',
        ),
        migrations.RemoveField(
            model_name='address',
            name='town_details',
        ),
    ]
